"""empty message

Revision ID: 1eecf0c5501a
Revises: 9adaf57edd4e
Create Date: 2025-09-12 11:34:40.524589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eecf0c5501a'
down_revision = '9adaf57edd4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###
