"""empty message

Revision ID: 22188b80758b
Revises: d446cfbf9793
Create Date: 2025-08-06 23:45:59.536827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22188b80758b'
down_revision = 'd446cfbf9793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
