"""empty message

Revision ID: 36455dd88cd8
Revises: d44fa2f03a0b
Create Date: 2025-08-07 21:46:54.781196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36455dd88cd8'
down_revision = 'd44fa2f03a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=32), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=32), nullable=True))

    with op.batch_alter_table('p_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=32), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=32), nullable=True))

    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=32), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('uuid')

    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_column('uuid')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('uuid')

    with op.batch_alter_table('p_categories', schema=None) as batch_op:
        batch_op.drop_column('uuid')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('uuid')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###
