"""empty message

Revision ID: 9adaf57edd4e
Revises: 6074a9eececa
Create Date: 2025-09-12 11:33:37.235995

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9adaf57edd4e'
down_revision = '6074a9eececa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_column('product_id')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('out_trade_no', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('total_fee', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('body', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('attach', sa.String(length=127), nullable=True))
        batch_op.add_column(sa.Column('trade_type', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('prepay_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('openid', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('bank_type', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('cash_fee', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('time_end', sa.String(length=14), nullable=True))
        batch_op.add_column(sa.Column('err_code', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('err_code_des', sa.String(length=128), nullable=True))
        batch_op.alter_column('transaction_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
               type_=sa.String(length=16),
               nullable=True)
        batch_op.create_unique_constraint(None, ['out_trade_no'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('paid_at')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('paid_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('status',
               existing_type=sa.String(length=16),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
               nullable=False)
        batch_op.alter_column('transaction_id',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               existing_nullable=True)
        batch_op.drop_column('err_code_des')
        batch_op.drop_column('err_code')
        batch_op.drop_column('time_end')
        batch_op.drop_column('cash_fee')
        batch_op.drop_column('bank_type')
        batch_op.drop_column('openid')
        batch_op.drop_column('prepay_id')
        batch_op.drop_column('trade_type')
        batch_op.drop_column('attach')
        batch_op.drop_column('body')
        batch_op.drop_column('total_fee')
        batch_op.drop_column('out_trade_no')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
