services:
  web:
    build: ..
    ports:
      - "5000:5000"
    volumes:
      - ..:/app
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app/__init__.py
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - fango-network
    command: /start.sh

  celery-worker:
    build: ..
    volumes:
      - ..:/app
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app/__init__.py
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - fango-network
    command: celery -A tasks.celery_app:celery worker --loglevel=info --queues=db_tasks,email_tasks

  celery-beat:
    build: ..
    volumes:
      - ..:/app
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app/__init__.py
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - fango-network
    command: celery -A tasks.celery_app:celery beat --loglevel=info

networks:
  fango-network:
    driver: bridge

volumes:
  logs: