services:
  web:
    build: ..
    ports:
      - "5000:5000"
    volumes:
      - ..:/app
      - ./logs:/app/logs
    env_file:
      - ../.env
    restart: unless-stopped
    networks:
      - fango-network
    command: /start-web.sh

  celery-worker:
    build: ..
    volumes:
      - ..:/app
      - ./logs:/app/logs
    env_file:
      - ../.env
    restart: unless-stopped
    networks:
      - fango-network
    command: /start-celery-worker.sh

  celery-beat:
    build: ..
    volumes:
      - ..:/app
      - ./logs:/app/logs
    env_file:
      - ../.env
    restart: unless-stopped
    networks:
      - fango-network
    command: /start-celery-beat.sh

networks:
  fango-network:
    driver: bridge

volumes:
  logs: