services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql-data: