services:
  web:
    build: ..
    ports:
      - "5000:5000"
    volumes:
      - ..:/app
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    env_file:
      - ../.env
    environment:
      - FLASK_APP=app/__init__.py
      - FLASK_ENV=${DEVELOPMENT:-production}
    extra_hosts:
      - "host.docker.internal:host-gateway"  # 添加 host.docker.internal 解析
    restart: unless-stopped
    networks:
      - fango-network
    command: /start-web.sh

  celery-worker:
    build: ..
    volumes:
      - ..:/app
      - ./logs:/app/logs
    env_file:
      - ../.env
    environment:
      - FLASK_APP=app/__init__.py
      - FLASK_ENV=${DEVELOPMENT:-production}
    extra_hosts:
      - "host.docker.internal:host-gateway"  # 添加 host.docker.internal 解析
    restart: unless-stopped
    networks:
      - fango-network
    command: /start-celery-worker.sh

  celery-beat:
    build: ..
    volumes:
      - ..:/app
      - ./logs:/app/logs
    env_file:
      - ../.env
    environment:
      - FLASK_APP=app/__init__.py
      - FLASK_ENV=${DEVELOPMENT:-production}
    extra_hosts:
      - "host.docker.internal:host-gateway"  # 添加 host.docker.internal 解析
    restart: unless-stopped
    networks:
      - fango-network
    command: /start-celery-beat.sh

networks:
  fango-network:
    external: true  # 使用外部网络