development:
  DEBUG: True
  SECRET_KEY: 'your_secret_key'
  SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://user:password@mysql:3306/fango?charset=utf8mb4'
  SQLALCHEMY_TRACK_MODIFICATIONS: False

production:
  DEBUG: False
  SECRET_KEY: 'your_prod_secret'
  SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://prod_user:prod_pass@mysql:3306/fango'