test:
  # base config
  DEBUG: False
  SECRET_KEY: 'your_prod_secret'
  SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://admin:123456@192.168.1.76:3306/fango'

  #rabbitmq config
  SQLALCHEMY_TRACK_MODIFICATIONS: False
  CELERY_BROKER_URL: 'amqp://guest:guest@192.168.3.66:5672//'
  CELERY_RESULT_BACKEND: 'redis://192.168.3.66:6379/0'
  CELERY_TIMEZONE: 'Asia/Shanghai'
  CELERY_ENABLE_UTC: True
  # upload files
  UPLOAD_FOLDER: 'uploads/images'
  MAX_UPLOAD_LENGTH: 16777216  # 16MB
  ALLOWED_EXTENSIONS: ['png', 'jpg', 'jpeg', 'gif', 'webp']
  BASE_URL: 'http://localhost:5000'

  # JWT config
  JWT_SECRET_KEY: 'your_jwt_secret_key_here'
  JWT_ACCESS_TOKEN_EXPIRES: 54000  # 15 Hours
  JWT_REFRESH_TOKEN_EXPIRES: 2592000  # 30 days

  # logger config
  LOG_LEVEL: 'INFO'
  LOG_TO_CONSOLE: true
  LOG_TO_MONGODB: true
  LOG_DIR: 'logs'

  # MongoDB config
  MONGODB_URI: 'mongodb://192.168.3.66:27017/'
  MONGODB_DB_NAME: 'fango_logs'
  MONGODB_LOG_COLLECTION: 'app_logs'

  # CORS config
  CORS_ORIGINS: ['http://localhost:3000', 'http://127.0.0.1:3000']
  CORS_SUPPORTS_CREDENTIALS: true
  CORS_METHODS: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
  CORS_ALLOW_HEADERS: ['Content-Type', 'Authorization']

  # admin config
  ADMIN_USERNAME: 'admin'
  ADMIN_EMAIL: 'admin@example.com'
  ADMIN_PASSWORD: 'admin123'
  ADMIN_PHONE: '18000000000'

  # wechat config
  WECHAT_APPID : 'wechat APPID'
  WECHAT_MCH_ID: '您的微信商户号'
  WECHAT_API_KEY: '您的微信支付API密钥'
  WECHAT_SANDBOX: True  # 是否使用沙箱环境
  WECHAT_NOTIFY_URL: 'https://vocallmall.cn/pay/wechat/notify' # 支付回调地址
