global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'fango-monitor'

rule_files:
  - alert.rules.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mongodb-exporter'
    static_configs:
      - targets: ['mongodb-exporter:9216']
    scrape_interval: 10s

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
    scrape_interval: 10s

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']